name: conformation

channels:
  - conda-forge
  - pytorch
  - rdkit
  - anaconda

dependencies:
  - pytorch>=1.5.1
  - rdkit>=2020.03.3
  - torchvision>=0.5.0
  - matplotlib>=3.2.2
  - numpy>=1.18.5
  - pot>=0.7.0
  - tensorboardx>=2.1
  - tensorflow>=1.14.0
  - tqdm>=4.47.0
  - scipy>=1.5.0
  - ipykernel>=5.3.0
  - pip>=20.1.1
  - scikit-learn>=0.23.1
  - pip:
      - py3Dmol>=0.8.0
      - typed-argument-parser>=1.5.1