name: conformation

channels:
  - conda-forge
  - pytorch
  - rdkit
  - anaconda

dependencies:
  - pytorch>=1.5.0
  - rdkit>=2020.03.3
  - torchvision>=0.5.0
  - matplotlib>=3.2.2
  - numpy>=1.18.5
  - tqdm>=4.47.0
  - scipy>=1.5.0